### ISSUE TITLE
Panic on startup: thread 'main' panicked at 'Failed to create client instance: StreamErr(Deserialize(Custom("invalid value: integer `1075838976`, expected variant index 0 <= i < 6")))', src/main.rs:116:10

### ISSUE THREAD

**Issue by Feriixu** [zesterer/teloren#21]
When launching with `$ RUST_BACKTRACE=full cargo r -- --username="<redacted>" --password="<redacted>" --character="<redacted>"`
produces the following output:

```
thread 'main' panicked at 'Failed to create client instance: StreamErr(Deserialize(Custom("invalid value: integer `1075838976`, expected variant index 0 <= i < 6")))', src/main.rs:116:10
stack backtrace:
   0:     0x55f1bf93935a - std::backtrace_rs::backtrace::libunwind::trace::h458cf307173bbb7e
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55f1bf93935a - std::backtrace_rs::backtrace::trace_unsynchronized::h3a86a735716b3162
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f1bf93935a - std::sys_common::backtrace::_print_fmt::h3c545795cfeff27f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55f1bf93935a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfc7d1e1184be2a4d
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55f1bf95dc6e - core::fmt::write::hc6ef11db54e29a99
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/core/src/fmt/mod.rs:1208:17
   5:     0x55f1bf9334e5 - std::io::Write::write_fmt::h5a19bdd460e661f7
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/io/mod.rs:1682:15
   6:     0x55f1bf939125 - std::sys_common::backtrace::_print::he565e8fb2a73c8ba
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55f1bf939125 - std::sys_common::backtrace::print::h3cdc14025f4ba73c
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55f1bf93aa2f - std::panicking::default_hook::{{closure}}::hc8d15b4a44e5c68f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:267:22
   9:     0x55f1bf93a76b - std::panicking::default_hook::hd5c34ad5ebbaa14f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:286:9
  10:     0x55f1bf93b13c - std::panicking::rust_panic_with_hook::h6b2d6d1ef385b7c1
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:688:13
  11:     0x55f1bf93aed9 - std::panicking::begin_panic_handler::{{closure}}::h906b0280d4771185
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:579:13
  12:     0x55f1bf93980c - std::sys_common::backtrace::__rust_end_short_backtrace::h75395d1a7d6a5847
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55f1bf93abe2 - rust_begin_unwind
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:575:5
  14:     0x55f1bf08fd73 - core::panicking::panic_fmt::h6c49d3b35c325f7f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/core/src/panicking.rs:65:14
  15:     0x55f1bf090033 - core::result::unwrap_failed::h75bd3efdc0b54835
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/core/src/result.rs:1791:5
  16:     0x55f1bf1cbc9c - core::result::Result<T,E>::expect::he4d8d8fb08e7967b
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/core/src/result.rs:1070:23
  17:     0x55f1bf1cbc9c - teloren::main::hfe17139bca294b91
                               at /home/elias/src/rust/teloren/src/main.rs:95:22
  18:     0x55f1bf18d513 - core::ops::function::FnOnce::call_once::h730281da163ec3ba
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/core/src/ops/function.rs:507:5
  19:     0x55f1bf18d513 - std::sys_common::backtrace::__rust_begin_short_backtrace::he9665da624c64b10
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/sys_common/backtrace.rs:121:18
  20:     0x55f1bf153f79 - std::rt::lang_start::{{closure}}::h05fee62c303784bd
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/rt.rs:166:18
  21:     0x55f1bf92c78c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hffbbdfa18f3caa37
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/core/src/ops/function.rs:606:13
  22:     0x55f1bf92c78c - std::panicking::try::do_call::h5f1eccb278bfdef0
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:483:40
  23:     0x55f1bf92c78c - std::panicking::try::h44ee1d2b114f2a71
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:447:19
  24:     0x55f1bf92c78c - std::panic::catch_unwind::hfa3abc533c03efe9
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panic.rs:137:14
  25:     0x55f1bf92c78c - std::rt::lang_start_internal::{{closure}}::hc50d6fdf27cb22a6
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/rt.rs:148:48
  26:     0x55f1bf92c78c - std::panicking::try::do_call::hf115fc25cae9b4f1
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:483:40
  27:     0x55f1bf92c78c - std::panicking::try::h2d3a9f6f9e803721
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panicking.rs:447:19
  28:     0x55f1bf92c78c - std::panic::catch_unwind::he37c9aaef9e33a66
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/panic.rs:137:14
  29:     0x55f1bf92c78c - std::rt::lang_start_internal::ha60ad03ba43b987f
                               at /rustc/1eb62b1235fd77200e6bd967d70e83c0f2497233/library/std/src/rt.rs:148:20
  30:     0x55f1bf1cd5bc - main
  31:     0x7f6f94787790 - <unknown>
  32:     0x7f6f9478784a - __libc_start_main
  33:     0x55f1bf0901c5 - _start
  34:                0x0 - <unknown>

```

**Comment by cpetig** [comment]
Please run cargo update before compiling teloren because the referenced veloren version from the last teloren check-in is outdated after one week.
